### ISSUE TITLE
Add ability to download tracks/albums/artists

### ISSUE THREAD

**Issue by vitaly-zdanevich** [DECE2183/yamusic-tui#10]

**Comment by DECE2183** [comment]
Hello, I don't think this is legal. The only thing I can do is add the ability to cache tracks to listen them while in offline (and this feature is in my plans, btw).

**Comment by vitaly-zdanevich** [comment]
> ability to cache tracks to listen them while in offline

ok :)

I hope that it will be usual files in usual folder - not blobs in SQLite.

**Comment by DECE2183** [comment]
This is the plan

**Comment by DECE2183** [comment]
Implemented in f0feed2 commit.
