### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by hirotasoshu** [DECE2183/yamusic-tui#3]
In about an hour of listening to music, RAM consumption increased from 15 MB to 330 MB. Is this the way it should be, or is there something wrong?

**Comment by DECE2183** [comment]
Yes, it must be a memory leak...

**Comment by DECE2183** [comment]
I think [this](https://github.com/DECE2183/yamusic-tui/commit/e6c15c616b7ee0fb9e32404091c6754f8a45227c) should solve it.

**Comment by hirotasoshu** [comment]
> I think [this](https://github.com/DECE2183/yamusic-tui/commit/e6c15c616b7ee0fb9e32404091c6754f8a45227c) should solve it.
Yeah, I can confirm that problem is resolved, thx
