### ISSUE TITLE
FeatureRequest: copy url

### ISSUE THREAD

**Issue by 13werwolf13** [DECE2183/yamusic-tui#6]
I think it’s a good idea to be able to get the url to a track in the clipboard by pressing one button (for example `c`) or a key combination (for example ctrl+u)

**Comment by DECE2183** [comment]
This feature has already been implemented. You can copy a track's URL by clicking the `share` button, which is also configurable and can be associated with any key or combination.

**Comment by 13werwolf13** [comment]
I'm sorry, for some reason the text of this particular function was left in the same color as the background. I did not see him.
