### ISSUE TITLE
Interacting with TUI using DBus

### ISSUE THREAD

**Issue by lsdrfrx** [DECE2183/yamusic-tui#7]
Hi! Great job, app is awesome!

I want to make widget for Qtile bar to display current track and control playback using this app. Is it possible using DBus?

**Comment by DECE2183** [comment]
No, this feature is not currently available. But I plan to add this in the future.

**Comment by DECE2183** [comment]
Implemented in [056f033](https://github.com/DECE2183/yamusic-tui/commit/056f033cc726ce2a5910fdd62ae9040e0cbf6bf8).
