### ISSUE TITLE
Readjusting to window size 

### ISSUE THREAD

**Issue by detache** [DECE2183/yamusic-tui#8]
After resizing window, all elements of "UI" is not align. Maybe add combination for reload "UI" elements or auto-ajustment function.
thx.
![ymtui](https://github.com/DECE2183/yamusic-tui/assets/3357485/2f49e22e-0495-48e1-b55f-150b3d540b87)

**Comment by DECE2183** [comment]
Yes, this is a known bug on Windows in the [charmbracelet/bubbletea](https://github.com/charmbracelet/bubbletea) framework that I use. For some reason it doesn't generate a resize event.

**Comment by DECE2183** [comment]
Fixed in some of the latest version of [charmbracelet/bubbletea](https://github.com/charmbracelet/bubbletea).
