### ISSUE TITLE
LastFM support?

### ISSUE THREAD

**Issue by al1-ce** [DECE2183/yamusic-tui#9]
Love the app! Been searching for something like that for a while now

Could you add lastfm support? I would make a pull request, but I'm not at all familiar with go

This would require adding auth and two POST requests one for setting currently listened track (better wait 2-5 secs before sending in case of skipping through tracks) and one for already listened (usually ok to trigger when listened for track for 20 secs)

Endpoints:
Auth - https://www.last.fm/api/authentication
Current track  - https://www.last.fm/api/show/track.updateNowPlaying
Listened track - https://www.last.fm/api/show/track.scrobble

Also would be nice to use
https://www.last.fm/api/show/track.love
https://www.last.fm/api/show/track.unlove

**Comment by DECE2183** [comment]
Such improvements will require much more complex work, for which I do not have enough resources. That's why, this application is focused exclusively on Yandex music.

**Comment by al1-ce** [comment]
I guess I could try learning go..

Would you accept PR?
